sudo: required

language: node_js

node_js:
  - "node"

services:
  - docker
  - mysql
  
before_script:
  - docker-compose up -d
  - sleep 10
  
script:
  - npm test
  
after_script:
  - docker-compose kill
