sudo: required

language: node_js

env:
  - NODE_ENV=development

node_js:
  - "node"

services:
  - docker
  
before_script:
  - sudo /etc/init.d/mysql stop
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d
  - sleep 30
  
script:
  - docker exec altraninnovationraceportal_web_1 npm test
  
after_script:
  - docker-compose kill
