sudo: required

language: node_js

node_js:
  - "node"

services:
  - docker
  - mysql
  
before_script:
  - sudo /etc/init.d/mysql stop
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d
  
script:
  - npm test
  
after_script:
  - docker-compose kill
