sudo: required

language: node_js

env:
  - NODE_ENV=test

node_js:
  - "node"

services:
  - docker
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE irp_test;'
  - cd src/

install:
  - npm install
  
before_script:
  - npm start
  
script:
  - npm test