version: '2'
services:
  web:
    build: "src"
    ports:
     - "80:8080"
  database:
    image: "mysql"
    command: "mysqld --user=root --verbose"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "irp"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"