version: '2'
services:
  web:
    build: "src"
    expose:
      - "8080"
    depends_on:
      - "database"
    environment:
      - NODE_ENV
      - DEBUG=$${DEBUG}
      - VIRTUAL_HOST=$${VIRTUAL_HOST}
    networks:
      back-tier:
  database:
    image: "mysql"
    command: "mysqld --user=root --verbose"
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: "irp"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      back-tier:
networks:
  back-tier:
  
