version: '2'
services:
  web:
    build: "src"
    expose:
      - "8080"
    links:
      - "database:database"
    environment:
      - NODE_ENV=$${NODE_ENV}
      - DEBUG=$${DEBUG}
      - VIRTUAL_HOST=$${VIRTUAL_HOST}
  database:
    image: "mysql"
    command: "mysqld --user=root --verbose"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "irp"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
